### ISSUE TITLE
bug: static/assetsのリンク切れが起きている

### ISSUE THREAD

**Issue by ensan-hcl** [ensan-hcl/azooKey-site#5]
もともと一部でstatic/assetsを直接指定して画像やファイルにリンクしていた部分があり、これらがbun run buildの際に名称が変わってしまうため、リンク切れを起こしている。

例：

```
期待しているパス：https://azookey.netlify.app/static/assets/customtabs_header0.png
実際のパス：https://azookey.netlify.app/assets/customtabs_header0-Bn35Bdf5.png
```

**Comment by ensan-hcl** [comment]
@L4Ph 元の挙動になるように修正できたりしますか？難しそうであれば別の対処を考えます。

**Comment by L4Ph** [comment]
@ensan-hcl ~~おそらくできると思います。~~
申し訳ないです。
もしかしたらファイルのパスは修正できないかもしれません。(どうやら画像はすべてassets以下にはいるみたいです。)

assignしていただけますか?

**Comment by L4Ph** [comment]
もしかしたら両立できたかもしれません。
ただ、`rollupOptions`での指定なので、将来的に使えなくなる可能性が(Viteの本番ビルドがrolldownに切り替わる可能性が高いため)あります。

![image](https://github.com/user-attachments/assets/21780199-5c0f-4985-87c3-65fb45a2d73a)

**Comment by ensan-hcl** [comment]
Resolved in #7
